// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rincon.Views.Data;

#nullable disable

namespace rincon.Migrations
{
    [DbContext(typeof(DBContex))]
    [Migration("20251119131149_migrations_002")]
    partial class migrations_002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rincon.Models.usuarioModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("Usuario_Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
